version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: messanger
    ports:
      - "8080:8080"
      - "8081:8081"

networks:
  messanger_network: {}
