create table if not exists "comment"
(
    id bigint generated by default as identity primary key,
    user_id bigint not null references "user"(id),
    discussion_id bigint not null references "discussion"(id),
    content text not null,
    created_at timestamp default now(),
    deleted_at timestamp
);