create table if not exists "chat_room"
(
    id bigint generated by default as identity primary key,
    user1 bigint not null references "user"(id),
    user2 bigint not null references "user"(id),
    created_at timestamp default now()
);