create table if not exists "discussion"
(
    id bigint generated by default as identity primary key,
    user_id bigint not null references "user"(id),
    title varchar(255) not null,
    content text not null,
    pinned_at timestamp,
    created_at timestamp default now(),
    deleted_at timestamp
);