create table if not exists "message"
(
    id bigint generated by default as identity primary key,
    sender bigint not null references "user"(id),
    receiver bigint not null references "user"(id),
    content text not null,
    chat_room bigint not null references "chat_room"(id),
    sent_at timestamp default now()
);