create table if not exists "user"
(
    id bigint generated by default as identity primary key,
    email varchar not null unique,
    password varchar not null,
    name varchar not null,
    role varchar not null
);